/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        map: "Kartta",
        appearance: "Ulkoasu",
        displayMode: "Näyttötila",
        displaySize: "Näytön koko",
        compareBasemaps: "Vertaa pohjakarttoja",
        showTheCompareButtonWhichPlaces: "Näytä vertailupainike, joka asettaa toisen pohjakartta kartalle vetävän jakajan taakse",
        portalSource: "Portaalilähde",
        useCustomPortal: "Käytä omaa portaalia",
        portalUrl: "Portaalin URL",
        browsePortalItems: "Selaa portaaliesineitä",
        searchByTitleOrItemId: "Etsi otsikon tai kohteen tunnisteen mukaan...",
        search: "Hae",
        noItemsFoundTryADifferent: "Kohteita ei löytynyt. Kokeile eri hakusanaa.",
        added: "Lisätty",
        add: "Lisää",
        importExportConfiguration: "Tuo tai vie asetukset",
        exportConfiguration: "Vie asetukset",
        exportYourBasemapConfigurationToXml: "Vie peruskarttaasetuksesi XML:ään varmuuskopiota tai jakamista varten.",
        generateXml: "Luo XML",
        downloadFile: "Lataa tiedosto",
        copyToClipboard: "Kopioi leikepöydälle",
        importConfiguration: "Tuo asetukset",
        importBasemapConfigurationFromXmlThis: "Tuo peruskarttaasetukset XML:stä. Tämä korvaa nykyiset peruskarttavalinnat.",
        loadFromFile: "Lataa tiedostosta",
        orPasteXml: "Tai liitä XML:",
        configurationImportedSuccessfully: "Asetukset tuotiin onnistuneesti!",
        clear: "Tyhjennä",
        noteImportingWillReplaceAllCurrent: "Huom: Tuonti korvaa kaikki nykyiset basemap valinnat, mutta ei muuta valittua karttaa.",
        selectedBasemaps: "Valitut pohjakartat",
        clickToSetTheDefaultBasemap: "Napsauta ...aseta oletuspohjakartta, kun sovellus lataa. Käytä nuolia tilata uudelleen.",
        moveUp: "Siirrä ylös",
        moveDown: "Siirry alas",
        defaultBasemap: "Oletuspohjakartta",
        setAsDefault: "Aseta oletusarvoksi",
        removeBasemap: "Poista pohjakartta",
        default: "(Varaus)",
        noBasemapsSelectedUseTheBrowse: "Peruskarttoja ei ole valittu. Lisää basemapit käyttämällä yllä olevaa Selaa portaalia.",
        help: "Ohje",
        showHelpGuide: "Näytä ohje",
        showTheQuestionMarkButtonThat: "Näytä kysymys-merkki-painike, joka avaa widget ohjeen"
      })
    }
  }
})
