/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        map: "Mappa",
        appearance: "Aspetto",
        displayMode: "Modalità di visualizzazione",
        displaySize: "Dimensioni dell'esposizione",
        compareBasemaps: "Confronta le mappe di base",
        showTheCompareButtonWhichPlaces: "Mostra il pulsante di confronto, che posiziona una seconda mappa di base sulla mappa dietro un divisore trascinabile",
        portalSource: "Fonte del portale",
        useCustomPortal: "Utilizzare il portale personalizzato",
        portalUrl: "URL del portale",
        browsePortalItems: "Sfoglia gli articoli del portale",
        searchByTitleOrItemId: "Ricerca per titolo o ID articolo...",
        search: "Cerca",
        noItemsFoundTryADifferent: "Nessun elemento trovato. Prova un termine di ricerca diverso.",
        added: "✓ Aggiunto",
        add: "Aggiungi",
        importExportConfiguration: "Importazione / Configurazione di esportazione",
        exportConfiguration: "Configurazione dell'esportazione",
        exportYourBasemapConfigurationToXml: "Esporta la configurazione di basemap in XML per il backup o la condivisione.",
        generateXml: "Generare XML",
        downloadFile: "Scarica File",
        copyToClipboard: "Copia negli appunti",
        importConfiguration: "Configurazione delle importazioni",
        importBasemapConfigurationFromXmlThis: "Importa la configurazione della basemap da XML. Questo sostituirà le selezioni basemap attuali.",
        loadFromFile: "Carica da File",
        orPasteXml: "O incollare XML:",
        configurationImportedSuccessfully: "Configurazione importata con successo!",
        clear: "Azzera",
        noteImportingWillReplaceAllCurrent: "Nota: Importazione sostituirà tutte le selezioni di basemap attuali, ma non cambierà il widget della mappa selezionata.",
        selectedBasemaps: "Basemaps selezionate",
        clickToSetTheDefaultBasemap: "Fare clic su ★ per impostare la mappa di base predefinita indicata quando l'app si carica. Utilizzare le frecce per riordinare.",
        moveUp: "Sposta su",
        moveDown: "Sposta giù",
        defaultBasemap: "Mappa di base predefinita",
        setAsDefault: "Impostare come predefinito",
        removeBasemap: "Rimuovi la mappa di base",
        default: "(Default)",
        noBasemapsSelectedUseTheBrowse: "Nessuna mappa di base selezionata. Utilizzare la sezione Sfoglia elementi portali per aggiungere le mappe di base.",
        help: "Guida",
        showHelpGuide: "Mostra la guida",
        showTheQuestionMarkButtonThat: "Mostra il pulsante di punto interrogativo che apre la guida di aiuto widget"
      })
    }
  }
})
