/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        map: "Karte",
        appearance: "Izskats",
        displayMode: "Attēlošanas režīms",
        displaySize: "Displeja izmērs",
        compareBasemaps: "Salīdzināt bāzes kartes",
        showTheCompareButtonWhichPlaces: "Rādīt salīdzināšanas pogu, kas noliek otru bāzes karti uz kartes aiz vilkamā dalītāja",
        portalSource: "Portālu avots",
        useCustomPortal: "Lietot pielāgotu portālu",
        portalUrl: "Portāla URL",
        browsePortalItems: "Pārlūkot portāla ierakstus",
        searchByTitleOrItemId: "Meklēt pēc nosaukuma vai posteņa ID...",
        search: "Meklēt",
        noItemsFoundTryADifferent: "Nav atrasta neviena vienība. Izmēģiniet citu meklēšanas terminu.",
        added: "י Pievienots",
        add: "Pievienot",
        importExportConfiguration: "Importēt / eksportēt konfigurāciju",
        exportConfiguration: "Eksportēt konfigurāciju",
        exportYourBasemapConfigurationToXml: "Eksportējiet savu bāzes kartes konfigurāciju XML dublēšanai vai kopīgošanai.",
        generateXml: "Vispārējs",
        downloadFile: "Lejupielādēt failu",
        copyToClipboard: "Kopēt starpliktuvē",
        importConfiguration: "Importēt konfigurāciju",
        importBasemapConfigurationFromXmlThis: "Importēt bāzes kartes konfigurāciju no XML. Šis aizstās jūsu pašreizējās bāzes kartes izvēles.",
        loadFromFile: "Ielādēt no faila",
        orPasteXml: "Vai ielīmēt XML:",
        configurationImportedSuccessfully: "Konfigurācija veiksmīgi importēta!",
        clear: "Notīrīt",
        noteImportingWillReplaceAllCurrent: "Piezīme: Importēšana aizstās visas pašreizējās bāzes kartes izvēles, bet nemainīs izvēlēto kartes logdaļu.",
        selectedBasemaps: "Izvēlētās bāzes kartes",
        clickToSetTheDefaultBasemap: "Noklikšķiniet uz ★, lai iestatītu noklusējuma bāzes kartes parādīts, kad lietotne slodzes. Izmantojiet bultiņas, lai pārkārtotu.",
        moveUp: "Pārvietot uz augšu",
        moveDown: "Pārvietot uz leju",
        defaultBasemap: "Noklusētā bāzes karte",
        setAsDefault: "Uzstādīt kā noklusēto",
        removeBasemap: "Izņemt pamatkarti",
        default: "(Noklusējums)",
        noBasemapsSelectedUseTheBrowse: "Nav izvēlētas bāzes kartes. Izmantojiet Pārlūkot Portālu Vienības sadaļu iepriekš, lai pievienotu bāzes kartes.",
        help: "Palīdzība",
        showHelpGuide: "Rādīt palīdzības ceļvedi",
        showTheQuestionMarkButtonThat: "Rādīt jautājumu zīmes pogu, kas atver logdaļu palīdzības rokasgrāmatu"
      })
    }
  }
})
