/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        map: "Kart",
        appearance: "Utseende",
        displayMode: "Visningsmodus",
        displaySize: "Visningsstørrelse",
        compareBasemaps: "Sammenlign basekart",
        showTheCompareButtonWhichPlaces: "Vis sammenligningsknappen, som plasserer et andre basiskart på kartet bak en drabar deler",
        portalSource: "Portalkilde",
        useCustomPortal: "Bruk egendefinert portal",
        portalUrl: "Portal URL",
        browsePortalItems: "Bla gjennom portalelementer",
        searchByTitleOrItemId: "Søk etter tittel eller element ID...",
        search: "Søk",
        noItemsFoundTryADifferent: "Ingen elementer funnet. Prøv et annet søkeord.",
        added: "✓ Lagt til",
        add: "Legg til",
        importExportConfiguration: "Importere / eksportere konfigurasjon",
        exportConfiguration: "Eksporter oppsett",
        exportYourBasemapConfigurationToXml: "Eksporter grunnkartkonfigurasjonen til XML for sikkerhetskopiering eller deling.",
        generateXml: "Opprett XML",
        downloadFile: "Last ned fil",
        copyToClipboard: "Kopier til utklippstavle",
        importConfiguration: "Importer konfigurasjon",
        importBasemapConfigurationFromXmlThis: "Importer grunnkartkonfigurasjon fra XML. Dette vil erstatte gjeldende basiskartvalg.",
        loadFromFile: "Last fra fil",
        orPasteXml: "Eller lim inn XML:",
        configurationImportedSuccessfully: "Konfigurasjon importert vellykket!",
        clear: "Fjern",
        noteImportingWillReplaceAllCurrent: "Merk: Importering vil erstatte alle gjeldende basekartvalg, men vil ikke endre den valgte kart widget.",
        selectedBasemaps: "Utvalgte basekart",
        clickToSetTheDefaultBasemap: "Klikk ★ for å angi standard grunnkart som vises når appen lastes. Bruk pilene til å omorganisere.",
        moveUp: "Flytt opp",
        moveDown: "Flytt ned",
        defaultBasemap: "Standard grunnkart",
        setAsDefault: "Sett som standard",
        removeBasemap: "Fjern grunnkart",
        default: "(Standard)",
        noBasemapsSelectedUseTheBrowse: "Ingen basiskart valgt. Bruk delen Bla gjennom portalelementer ovenfor for å legge til basekart.",
        help: "Hjelp",
        showHelpGuide: "Vis hjelpguide",
        showTheQuestionMarkButtonThat: "Vis spørsmålsmerkeknappen som åpner widget-hjelpeguiden"
      })
    }
  }
})
