/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        map: "Mapa",
        appearance: "Aparência",
        displayMode: "Modo de exibição",
        displaySize: "Tamanho da exibição",
        compareBasemaps: "Compare mapas de base",
        showTheCompareButtonWhichPlaces: "Mostre o botão de comparação, que coloca um segundo mapa no mapa atrás de um divisor arrastável.",
        portalSource: "Fonte do Portal",
        useCustomPortal: "Use o portal personalizado.",
        portalUrl: "URL do portal",
        browsePortalItems: "Navegue pelos itens do Portal.",
        searchByTitleOrItemId: "Procure pelo título ou item ID...",
        search: "Pesquisar",
        noItemsFoundTryADifferent: "Nenhum item encontrado. Tente um termo de busca diferente.",
        added: "Adicionado",
        add: "Adicionar",
        importExportConfiguration: "Configuração de Importação / Exportação",
        exportConfiguration: "Configuração de Exportação",
        exportYourBasemapConfigurationToXml: "Exportar sua configuração do mapa de base para XML para backup ou compartilhamento.",
        generateXml: "Gerar XML",
        downloadFile: "Arquivo de Download",
        copyToClipboard: "Copiar para área de transferência",
        importConfiguration: "Configuração da Importação",
        importBasemapConfigurationFromXmlThis: "Importar configuração do mapa base do XML. Isso substituirá suas seleções atuais.",
        loadFromFile: "Carregar do Arquivo",
        orPasteXml: "Ou colar XML:",
        configurationImportedSuccessfully: "Configuração importada com sucesso!",
        clear: "Limpar",
        noteImportingWillReplaceAllCurrent: "Nota: Importar substituirá todas as seleções atuais do mapa de base, mas não mudará o widget selecionado do mapa.",
        selectedBasemaps: "Mapas de base selecionados",
        clickToSetTheDefaultBasemap: "Clique em ★ para definir o mapa padrão mostrado quando o aplicativo carrega. Use flechas para reordenar.",
        moveUp: "Mover para Cima",
        moveDown: "Mover para baixo",
        defaultBasemap: "Mapa de base padrão",
        setAsDefault: "Definir como padrão",
        removeBasemap: "Remova o mapa base",
        default: "(Padrão)",
        noBasemapsSelectedUseTheBrowse: "Nenhum mapa de base selecionado. Use a seção de itens do portal para adicionar mapas de base.",
        help: "Ajuda",
        showHelpGuide: "Mostre guia de ajuda.",
        showTheQuestionMarkButtonThat: "Mostre o botão de ponto de interrogação que abre o guia de ajuda do widget."
      })
    }
  }
})
