/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        map: "Hartă",
        appearance: "Aspect",
        displayMode: "Mod afișare",
        displaySize: "Dimensiune afișare",
        compareBasemaps: "Compară bazale",
        showTheCompareButtonWhichPlaces: "Afișează butonul de comparare, care plasează o a doua bază pe hartă în spatele unui separator dragable",
        portalSource: "Sursa portalului",
        useCustomPortal: "Folosește portalul personalizat",
        portalUrl: "URL portal",
        browsePortalItems: "Navighează elementele portalului",
        searchByTitleOrItemId: "Caută după titlu sau element ID...",
        search: "Căutare",
        noItemsFoundTryADifferent: "Nu am găsit nimic. Încearcă un alt termen de căutare.",
        added: "Adăugat",
        add: "Adăugare",
        importExportConfiguration: "Importă / exportă configurare",
        exportConfiguration: "Configurare exportă",
        exportYourBasemapConfigurationToXml: "Exportaţi configuraţia de bază în XML pentru backup sau partajare.",
        generateXml: "Generează XML",
        downloadFile: "Descarcă fișierul",
        copyToClipboard: "Copiere în clipboard",
        importConfiguration: "Configurare importă",
        importBasemapConfigurationFromXmlThis: "Importă configurarea datelor de bază din XML. Acest lucru va înlocui selecţiile actuale de bază.",
        loadFromFile: "Încarcă din fișier",
        orPasteXml: "Sau lipi XML:",
        configurationImportedSuccessfully: "Configurare importată cu succes!",
        clear: "Golire",
        noteImportingWillReplaceAllCurrent: "Notă: Importarea va înlocui toate selecţiile curente de bază, dar nu va schimba widget-ul harta selectat.",
        selectedBasemaps: "Comment",
        clickToSetTheDefaultBasemap: "Faceți clic pe Foloseste sagetile pentru a reordona.",
        moveUp: "Deplasare în sus",
        moveDown: "Deplasare în jos",
        defaultBasemap: "Hartă de bază implicită",
        setAsDefault: "Stabilește ca implicit",
        removeBasemap: "Elimină harta bazei",
        default: "(Default)",
        noBasemapsSelectedUseTheBrowse: "Nu s-a selectat niciun basemaps. Utilizați secțiunea de elemente de portal de navigare de mai sus pentru a adăuga basemaps.",
        help: "Ajutor",
        showHelpGuide: "Arată ghidul de ajutor",
        showTheQuestionMarkButtonThat: "Arată butonul semn de întrebare care deschide ghidul de ajutor widget"
      })
    }
  }
})
