/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        map: "Карта",
        appearance: "Оформление",
        displayMode: "Режим отображения",
        displaySize: "Размер изображения",
        compareBasemaps: "Сравнение базовых карт",
        showTheCompareButtonWhichPlaces: "Покажите кнопку сравнения, которая размещает вторую базовую карту на карте за перетаскивающимся делителем",
        portalSource: "Портал Источник",
        useCustomPortal: "Используйте пользовательский портал",
        portalUrl: "Портал URL",
        browsePortalItems: "Просмотреть Portal Items",
        searchByTitleOrItemId: "Поиск по заголовку или элементу ID...",
        search: "Поиск",
        noItemsFoundTryADifferent: "Никаких предметов не найдено. Попробуйте другой поисковый запрос.",
        added: "Добавлено",
        add: "Добавить",
        importExportConfiguration: "Конфигурация импорта/экспорта",
        exportConfiguration: "Конфигурация экспорта",
        exportYourBasemapConfigurationToXml: "Экспортируйте конфигурацию базовой карты в XML для резервного копирования или совместного использования.",
        generateXml: "Генерировать XML",
        downloadFile: "Скачать файл",
        copyToClipboard: "Копировать в буфер обмена",
        importConfiguration: "Конфигурация импорта",
        importBasemapConfigurationFromXmlThis: "Конфигурация базовой карты импорта из XML. Это заменит ваш текущий выбор базовой карты.",
        loadFromFile: "Загрузка из файла",
        orPasteXml: "Или вставить XML:",
        configurationImportedSuccessfully: "Конфигурация успешно импортируется!",
        clear: "Очистить",
        noteImportingWillReplaceAllCurrent: "Примечание: Импорт заменит все текущие параметры базовой карты, но не изменит выбранный виджет карты.",
        selectedBasemaps: "Выбранные Basemaps",
        clickToSetTheDefaultBasemap: "Нажмите ★, чтобы установить базовую карту по умолчанию, показанную при загрузке приложения. Используйте стрелки для переупорядочения.",
        moveUp: "Выше",
        moveDown: "Ниже",
        defaultBasemap: "Базовая карта по умолчанию",
        setAsDefault: "Устанавливается как default",
        removeBasemap: "Удалить basemap",
        default: "(Неисправность)",
        noBasemapsSelectedUseTheBrowse: "Никаких базовых карт не выбрано. Используйте раздел Browse Portal Items выше, чтобы добавить базовые карты.",
        help: "Справка",
        showHelpGuide: "Показать справочник",
        showTheQuestionMarkButtonThat: "Покажите кнопку вопрос-марка, которая открывает руководство по помощи виджета"
      })
    }
  }
})
