/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        map: "地图",
        appearance: "外观",
        displayMode: "Display Mode",
        displaySize: "Display Size",
        compareBasemaps: "Compare basemaps",
        showTheCompareButtonWhichPlaces: "Show the compare button, which places a second basemap on the map behind a draggable divider",
        portalSource: "Portal Source",
        useCustomPortal: "Use custom portal",
        portalUrl: "Portal URL",
        browsePortalItems: "Browse Portal Items",
        searchByTitleOrItemId: "Search by title or item ID...",
        search: "搜索",
        noItemsFoundTryADifferent: "No items found. Try a different search term.",
        added: "✓ Added",
        add: "添加",
        importExportConfiguration: "Import / Export Configuration",
        exportConfiguration: "Export Configuration",
        exportYourBasemapConfigurationToXml: "Export your basemap configuration to XML for backup or sharing.",
        generateXml: "Generate XML",
        downloadFile: "Download File",
        copyToClipboard: "复制到剪贴板",
        importConfiguration: "Import Configuration",
        importBasemapConfigurationFromXmlThis: "Import basemap configuration from XML. This will replace your current basemap selections.",
        loadFromFile: "Load from File",
        orPasteXml: "Or paste XML:",
        configurationImportedSuccessfully: "Configuration imported successfully!",
        clear: "清除",
        noteImportingWillReplaceAllCurrent: "Note: Importing will replace all current basemap selections but will not change the selected map widget.",
        selectedBasemaps: "Selected Basemaps",
        clickToSetTheDefaultBasemap: "Click ★ to set the default basemap shown when the app loads. Use arrows to reorder.",
        moveUp: "上移",
        moveDown: "下移",
        defaultBasemap: "Default basemap",
        setAsDefault: "Set as default",
        removeBasemap: "Remove basemap",
        default: "(Default)",
        noBasemapsSelectedUseTheBrowse: "No basemaps selected. Use the Browse Portal Items section above to add basemaps.",
        help: "帮助",
        showHelpGuide: "Show help guide",
        showTheQuestionMarkButtonThat: "Show the question-mark button that opens the widget help guide"
      })
    }
  }
})
